name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: segator/emule
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
